revoke all on function public.app_build_public_session_payload(uuid, uuid, uuid) from anon, authenticated;
revoke all on function public.app_effective_enabled_modules(uuid) from anon, authenticated;
revoke all on function public.app_sync_commerce_modules(uuid, text, jsonb) from anon, authenticated;
revoke all on function public.import_snapshot_to_core(text) from authenticated;
revoke all on function public.upsert_commerce_profile(text, text, text, text) from authenticated;
revoke all on function public.bootstrap_control_user(text) from authenticated;
revoke all on function public.bootstrap_control_user(text, text) from authenticated;

alter function public.app_plan_module_keys(text) set search_path = public, extensions;
alter function public.app_effective_enabled_modules(uuid) set search_path = public, extensions;
alter function public.app_sync_commerce_modules(uuid, text, jsonb) set search_path = public, extensions;
alter function public.app_build_public_session_payload(uuid, uuid, uuid) set search_path = public, extensions;
alter function public.app_get_setup_status(text) set search_path = public, extensions;
alter function public.app_setup_instance(text, text, text, text, text, text, text, text, text, text) set search_path = public, extensions;
alter function public.app_public_sign_in(text, text, text) set search_path = public, extensions;
alter function public.app_public_sign_out(text) set search_path = public, extensions;
alter function public.app_public_restore_session(text) set search_path = public, extensions;
alter function public.app_public_request_password_reset(text) set search_path = public, extensions;
alter function public.app_public_close_cash_session(text, text, numeric) set search_path = public, extensions;
alter function public.app_public_create_cash_movement(text, text, text, numeric, text) set search_path = public, extensions;
alter function public.app_public_create_sale(text, text, text, text, numeric, text, boolean, boolean, numeric, numeric, numeric, numeric, jsonb, text, text) set search_path = public, extensions;
alter function public.app_public_open_cash_session(text, text, numeric) set search_path = public, extensions;
alter function public.app_public_toggle_user_active(text, text, boolean) set search_path = public, extensions;
alter function public.app_public_update_commerce_profile(text, text, text, text, text) set search_path = public, extensions;
alter function public.app_public_update_commerce_runtime(text, text, jsonb, boolean) set search_path = public, extensions;
alter function public.app_public_upsert_branch(text, text, text, text, text, boolean) set search_path = public, extensions;
alter function public.app_public_upsert_customer(text, text, text, text, text, numeric, text, text) set search_path = public, extensions;
alter function public.app_public_upsert_document(text, text, text, text, text, text, text, text, text, text, text, numeric, jsonb) set search_path = public, extensions;
alter function public.app_public_upsert_product(text, text, text, text, text, numeric, numeric, numeric, numeric, text, boolean, text) set search_path = public, extensions;
alter function public.app_public_upsert_purchase_receipt(text, text, text, text, text, numeric, numeric, text, text) set search_path = public, extensions;
alter function public.app_public_upsert_register(text, text, text, text, text, text, boolean) set search_path = public, extensions;
alter function public.app_public_upsert_supplier(text, text, text, text, text, text, text, numeric, date, text, boolean) set search_path = public, extensions;
alter function public.app_public_upsert_user(text, text, text, text, text, text, boolean) set search_path = public, extensions;
alter function public.app_sync_password_from_auth(text) set search_path = public, extensions;
